-- Seed the global verb catalog (VERBS.md). Generated from server/db/verbs.ts.
-- Idempotent: existing infinitives are left untouched. Applied to dev via
-- `npm run db:migrate` and to prod by the CI migrate job on push to main.
INSERT INTO "verbs" ("infinitive", "english", "regularity", "frequency_rank", "form_ich", "form_du", "form_er", "form_wir", "form_ihr", "form_sie") VALUES
  ('sein', 'to be', 'irregular', 1, 'bin', 'bist', 'ist', 'sind', 'seid', 'sind'),
  ('haben', 'to have', 'irregular', 2, 'habe', 'hast', 'hat', 'haben', 'habt', 'haben'),
  ('werden', 'to become', 'irregular', 3, 'werde', 'wirst', 'wird', 'werden', 'werdet', 'werden'),
  ('können', 'to be able to (can)', 'irregular', 4, 'kann', 'kannst', 'kann', 'können', 'könnt', 'können'),
  ('müssen', 'to have to (must)', 'irregular', 5, 'muss', 'musst', 'muss', 'müssen', 'müsst', 'müssen'),
  ('sagen', 'to say', 'regular', 6, 'sage', 'sagst', 'sagt', 'sagen', 'sagt', 'sagen'),
  ('machen', 'to make / do', 'regular', 7, 'mache', 'machst', 'macht', 'machen', 'macht', 'machen'),
  ('geben', 'to give', 'irregular', 8, 'gebe', 'gibst', 'gibt', 'geben', 'gebt', 'geben'),
  ('kommen', 'to come', 'regular', 9, 'komme', 'kommst', 'kommt', 'kommen', 'kommt', 'kommen'),
  ('sollen', 'should / ought to', 'irregular', 10, 'soll', 'sollst', 'soll', 'sollen', 'sollt', 'sollen'),
  ('wollen', 'to want', 'irregular', 11, 'will', 'willst', 'will', 'wollen', 'wollt', 'wollen'),
  ('gehen', 'to go', 'regular', 12, 'gehe', 'gehst', 'geht', 'gehen', 'geht', 'gehen'),
  ('wissen', 'to know (a fact)', 'irregular', 13, 'weiß', 'weißt', 'weiß', 'wissen', 'wisst', 'wissen'),
  ('sehen', 'to see', 'irregular', 14, 'sehe', 'siehst', 'sieht', 'sehen', 'seht', 'sehen'),
  ('lassen', 'to let / leave', 'irregular', 15, 'lasse', 'lässt', 'lässt', 'lassen', 'lasst', 'lassen'),
  ('stehen', 'to stand', 'regular', 16, 'stehe', 'stehst', 'steht', 'stehen', 'steht', 'stehen'),
  ('finden', 'to find', 'regular', 17, 'finde', 'findest', 'findet', 'finden', 'findet', 'finden'),
  ('bleiben', 'to stay', 'regular', 18, 'bleibe', 'bleibst', 'bleibt', 'bleiben', 'bleibt', 'bleiben'),
  ('liegen', 'to lie (be located)', 'regular', 19, 'liege', 'liegst', 'liegt', 'liegen', 'liegt', 'liegen'),
  ('heißen', 'to be called', 'regular', 20, 'heiße', 'heißt', 'heißt', 'heißen', 'heißt', 'heißen'),
  ('denken', 'to think', 'regular', 21, 'denke', 'denkst', 'denkt', 'denken', 'denkt', 'denken'),
  ('nehmen', 'to take', 'irregular', 22, 'nehme', 'nimmst', 'nimmt', 'nehmen', 'nehmt', 'nehmen'),
  ('tun', 'to do', 'irregular', 23, 'tue', 'tust', 'tut', 'tun', 'tut', 'tun'),
  ('dürfen', 'to be allowed to (may)', 'irregular', 24, 'darf', 'darfst', 'darf', 'dürfen', 'dürft', 'dürfen'),
  ('glauben', 'to believe', 'regular', 25, 'glaube', 'glaubst', 'glaubt', 'glauben', 'glaubt', 'glauben'),
  ('halten', 'to hold / stop', 'irregular', 26, 'halte', 'hältst', 'hält', 'halten', 'haltet', 'halten'),
  ('nennen', 'to name / call', 'regular', 27, 'nenne', 'nennst', 'nennt', 'nennen', 'nennt', 'nennen'),
  ('mögen', 'to like', 'irregular', 28, 'mag', 'magst', 'mag', 'mögen', 'mögt', 'mögen'),
  ('zeigen', 'to show', 'regular', 29, 'zeige', 'zeigst', 'zeigt', 'zeigen', 'zeigt', 'zeigen'),
  ('führen', 'to lead', 'regular', 30, 'führe', 'führst', 'führt', 'führen', 'führt', 'führen'),
  ('sprechen', 'to speak', 'irregular', 31, 'spreche', 'sprichst', 'spricht', 'sprechen', 'sprecht', 'sprechen'),
  ('bringen', 'to bring', 'regular', 32, 'bringe', 'bringst', 'bringt', 'bringen', 'bringt', 'bringen'),
  ('leben', 'to live', 'regular', 33, 'lebe', 'lebst', 'lebt', 'leben', 'lebt', 'leben'),
  ('fahren', 'to drive / go', 'irregular', 34, 'fahre', 'fährst', 'fährt', 'fahren', 'fahrt', 'fahren'),
  ('meinen', 'to mean / think', 'regular', 35, 'meine', 'meinst', 'meint', 'meinen', 'meint', 'meinen'),
  ('fragen', 'to ask', 'regular', 36, 'frage', 'fragst', 'fragt', 'fragen', 'fragt', 'fragen'),
  ('kennen', 'to know (be acquainted)', 'regular', 37, 'kenne', 'kennst', 'kennt', 'kennen', 'kennt', 'kennen'),
  ('gelten', 'to be valid / count', 'irregular', 38, 'gelte', 'giltst', 'gilt', 'gelten', 'geltet', 'gelten'),
  ('stellen', 'to place / put', 'regular', 39, 'stelle', 'stellst', 'stellt', 'stellen', 'stellt', 'stellen'),
  ('spielen', 'to play', 'regular', 40, 'spiele', 'spielst', 'spielt', 'spielen', 'spielt', 'spielen'),
  ('arbeiten', 'to work', 'regular', 41, 'arbeite', 'arbeitest', 'arbeitet', 'arbeiten', 'arbeitet', 'arbeiten'),
  ('brauchen', 'to need', 'regular', 42, 'brauche', 'brauchst', 'braucht', 'brauchen', 'braucht', 'brauchen'),
  ('folgen', 'to follow', 'regular', 43, 'folge', 'folgst', 'folgt', 'folgen', 'folgt', 'folgen'),
  ('lernen', 'to learn', 'regular', 44, 'lerne', 'lernst', 'lernt', 'lernen', 'lernt', 'lernen'),
  ('verstehen', 'to understand', 'regular', 45, 'verstehe', 'verstehst', 'versteht', 'verstehen', 'versteht', 'verstehen'),
  ('setzen', 'to set / put', 'regular', 46, 'setze', 'setzt', 'setzt', 'setzen', 'setzt', 'setzen'),
  ('bekommen', 'to receive / get', 'regular', 47, 'bekomme', 'bekommst', 'bekommt', 'bekommen', 'bekommt', 'bekommen'),
  ('beginnen', 'to begin', 'regular', 48, 'beginne', 'beginnst', 'beginnt', 'beginnen', 'beginnt', 'beginnen'),
  ('erzählen', 'to tell / narrate', 'regular', 49, 'erzähle', 'erzählst', 'erzählt', 'erzählen', 'erzählt', 'erzählen'),
  ('versuchen', 'to try', 'regular', 50, 'versuche', 'versuchst', 'versucht', 'versuchen', 'versucht', 'versuchen'),
  ('schreiben', 'to write', 'regular', 51, 'schreibe', 'schreibst', 'schreibt', 'schreiben', 'schreibt', 'schreiben'),
  ('laufen', 'to run / walk', 'irregular', 52, 'laufe', 'läufst', 'läuft', 'laufen', 'lauft', 'laufen'),
  ('essen', 'to eat', 'irregular', 53, 'esse', 'isst', 'isst', 'essen', 'esst', 'essen'),
  ('trinken', 'to drink', 'regular', 54, 'trinke', 'trinkst', 'trinkt', 'trinken', 'trinkt', 'trinken'),
  ('lesen', 'to read', 'irregular', 55, 'lese', 'liest', 'liest', 'lesen', 'lest', 'lesen'),
  ('helfen', 'to help', 'irregular', 56, 'helfe', 'hilfst', 'hilft', 'helfen', 'helft', 'helfen'),
  ('verlieren', 'to lose', 'regular', 57, 'verliere', 'verlierst', 'verliert', 'verlieren', 'verliert', 'verlieren'),
  ('treffen', 'to meet / hit', 'irregular', 58, 'treffe', 'triffst', 'trifft', 'treffen', 'trefft', 'treffen'),
  ('tragen', 'to carry / wear', 'irregular', 59, 'trage', 'trägst', 'trägt', 'tragen', 'tragt', 'tragen'),
  ('scheinen', 'to seem / shine', 'regular', 60, 'scheine', 'scheinst', 'scheint', 'scheinen', 'scheint', 'scheinen'),
  ('fallen', 'to fall', 'irregular', 61, 'falle', 'fällst', 'fällt', 'fallen', 'fallt', 'fallen'),
  ('schlagen', 'to hit / beat', 'irregular', 62, 'schlage', 'schlägst', 'schlägt', 'schlagen', 'schlagt', 'schlagen'),
  ('gewinnen', 'to win', 'regular', 63, 'gewinne', 'gewinnst', 'gewinnt', 'gewinnen', 'gewinnt', 'gewinnen'),
  ('bieten', 'to offer', 'regular', 64, 'biete', 'bietest', 'bietet', 'bieten', 'bietet', 'bieten'),
  ('schließen', 'to close', 'regular', 65, 'schließe', 'schließt', 'schließt', 'schließen', 'schließt', 'schließen'),
  ('entscheiden', 'to decide', 'regular', 66, 'entscheide', 'entscheidest', 'entscheidet', 'entscheiden', 'entscheidet', 'entscheiden'),
  ('warten', 'to wait', 'regular', 67, 'warte', 'wartest', 'wartet', 'warten', 'wartet', 'warten'),
  ('erklären', 'to explain', 'regular', 68, 'erkläre', 'erklärst', 'erklärt', 'erklären', 'erklärt', 'erklären'),
  ('schaffen', 'to manage / create', 'regular', 69, 'schaffe', 'schaffst', 'schafft', 'schaffen', 'schafft', 'schaffen'),
  ('gehören', 'to belong', 'regular', 70, 'gehöre', 'gehörst', 'gehört', 'gehören', 'gehört', 'gehören'),
  ('erreichen', 'to reach / achieve', 'regular', 71, 'erreiche', 'erreichst', 'erreicht', 'erreichen', 'erreicht', 'erreichen'),
  ('vergessen', 'to forget', 'irregular', 72, 'vergesse', 'vergisst', 'vergisst', 'vergessen', 'vergesst', 'vergessen'),
  ('wachsen', 'to grow', 'irregular', 73, 'wachse', 'wächst', 'wächst', 'wachsen', 'wachst', 'wachsen'),
  ('gefallen', 'to please / be liked', 'irregular', 74, 'gefalle', 'gefällst', 'gefällt', 'gefallen', 'gefallt', 'gefallen'),
  ('schlafen', 'to sleep', 'irregular', 75, 'schlafe', 'schläfst', 'schläft', 'schlafen', 'schlaft', 'schlafen'),
  ('verbringen', 'to spend (time)', 'regular', 76, 'verbringe', 'verbringst', 'verbringt', 'verbringen', 'verbringt', 'verbringen'),
  ('legen', 'to lay / put down', 'regular', 77, 'lege', 'legst', 'legt', 'legen', 'legt', 'legen'),
  ('öffnen', 'to open', 'regular', 78, 'öffne', 'öffnest', 'öffnet', 'öffnen', 'öffnet', 'öffnen'),
  ('kaufen', 'to buy', 'regular', 79, 'kaufe', 'kaufst', 'kauft', 'kaufen', 'kauft', 'kaufen'),
  ('hören', 'to hear', 'regular', 80, 'höre', 'hörst', 'hört', 'hören', 'hört', 'hören'),
  ('wohnen', 'to live / reside', 'regular', 81, 'wohne', 'wohnst', 'wohnt', 'wohnen', 'wohnt', 'wohnen'),
  ('studieren', 'to study', 'regular', 82, 'studiere', 'studierst', 'studiert', 'studieren', 'studiert', 'studieren'),
  ('lieben', 'to love', 'regular', 83, 'liebe', 'liebst', 'liebt', 'lieben', 'liebt', 'lieben'),
  ('reisen', 'to travel', 'regular', 84, 'reise', 'reist', 'reist', 'reisen', 'reist', 'reisen'),
  ('kochen', 'to cook', 'regular', 85, 'koche', 'kochst', 'kocht', 'kochen', 'kocht', 'kochen'),
  ('singen', 'to sing', 'regular', 86, 'singe', 'singst', 'singt', 'singen', 'singt', 'singen'),
  ('tanzen', 'to dance', 'regular', 87, 'tanze', 'tanzt', 'tanzt', 'tanzen', 'tanzt', 'tanzen'),
  ('lachen', 'to laugh', 'regular', 88, 'lache', 'lachst', 'lacht', 'lachen', 'lacht', 'lachen'),
  ('rufen', 'to call / shout', 'regular', 89, 'rufe', 'rufst', 'ruft', 'rufen', 'ruft', 'rufen'),
  ('waschen', 'to wash', 'irregular', 90, 'wasche', 'wäschst', 'wäscht', 'waschen', 'wascht', 'waschen'),
  ('ziehen', 'to pull / move', 'regular', 91, 'ziehe', 'ziehst', 'zieht', 'ziehen', 'zieht', 'ziehen'),
  ('bezahlen', 'to pay', 'regular', 92, 'bezahle', 'bezahlst', 'bezahlt', 'bezahlen', 'bezahlt', 'bezahlen'),
  ('verkaufen', 'to sell', 'regular', 93, 'verkaufe', 'verkaufst', 'verkauft', 'verkaufen', 'verkauft', 'verkaufen'),
  ('antworten', 'to answer', 'regular', 94, 'antworte', 'antwortest', 'antwortet', 'antworten', 'antwortet', 'antworten'),
  ('vergleichen', 'to compare', 'regular', 95, 'vergleiche', 'vergleichst', 'vergleicht', 'vergleichen', 'vergleicht', 'vergleichen'),
  ('empfehlen', 'to recommend', 'irregular', 96, 'empfehle', 'empfiehlst', 'empfiehlt', 'empfehlen', 'empfehlt', 'empfehlen'),
  ('sterben', 'to die', 'irregular', 97, 'sterbe', 'stirbst', 'stirbt', 'sterben', 'sterbt', 'sterben'),
  ('werfen', 'to throw', 'irregular', 98, 'werfe', 'wirfst', 'wirft', 'werfen', 'werft', 'werfen'),
  ('treten', 'to step / kick', 'irregular', 99, 'trete', 'trittst', 'tritt', 'treten', 'tretet', 'treten')
ON CONFLICT ("infinitive") DO NOTHING;
