-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 75: Swedish cognate for uns (us)
UPDATE "cards" SET "swedish" = 'oss'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 75;

-- rank 495: Swedish cognate for euch (you pl.)
UPDATE "cards" SET "swedish" = 'er'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 495;

-- rank 340: Swedish cognate for tatsächlich (actual)
UPDATE "cards" SET "swedish" = 'faktisk'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 340;

-- rank 321: Swedish cognate for steigen (to climb/rise)
UPDATE "cards" SET "swedish" = 'stiga'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 321;

-- rank 302: Swedish cognate for deutlich (clear)
UPDATE "cards" SET "swedish" = 'tydlig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 302;

-- rank 299: Swedish cognate for handeln (to act/trade)
UPDATE "cards" SET "swedish" = 'handla'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 299;

-- rank 297: Swedish cognate for die Zahl (number)
UPDATE "cards" SET "swedish" = 'tal'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 297;

-- rank 280: Swedish cognate for bestimmt (certain/definite)
UPDATE "cards" SET "swedish" = 'bestämd'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 280;

-- rank 279: Swedish for überhaupt (at all)
UPDATE "cards" SET "swedish" = 'över huvud taget'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 279;

-- rank 523: Swedish cognate for annehmen (to assume/accept)
UPDATE "cards" SET "swedish" = 'anta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 523;
