-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 569: Swedish cognate for der Begriff (concept/term)
UPDATE "cards" SET "swedish" = 'begrepp'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 569;

-- rank 568: Swedish cognate for aktuell (current)
UPDATE "cards" SET "swedish" = 'aktuell'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 568;

-- rank 419: Swedish cognate for bestimmen (to decide/determine)
UPDATE "cards" SET "swedish" = 'bestämma'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 419;

-- rank 216: Swedish "känna någon" pins kennen to knowing a person (vs. wissen)
UPDATE "cards" SET "swedish" = 'känna någon'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 216;

-- rank 189: Swedish cognate for wirklich (real/actual)
UPDATE "cards" SET "swedish" = 'verklig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 189;

-- rank 560: Swedish "bo" maps wohnen (to live/reside) better than English "to live"
UPDATE "cards" SET "swedish" = 'bo'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 560;

-- rank 566: Swedish cognate for merken (to notice)
UPDATE "cards" SET "swedish" = 'märka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 566;
