-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 224: plurale tantum: die Leute (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 224;

-- rank 404: plurale tantum: die Eltern (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 404;

-- rank 564: plurale tantum: die Kosten (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 564;

-- rank 574: plural of das Datum, used as plurale tantum: die Daten
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 574;

-- rank 951: plural of das Medium, used as plurale tantum: die Medien
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 951;

-- rank 2853: plurale tantum: die Schulden (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2853;

-- rank 3448: plurale tantum: die Ferien (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3448;

-- rank 3929: plural noun: die Geschwister (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3929;

-- rank 4068: plural noun: die Taliban (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4068;

-- rank 4099: plural-only proper noun: die Alpen (article-less in the source deck)
UPDATE "cards" SET "article" = 'die'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4099;
