-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 623: Swedish cognate "ske" pins geschehen (to happen/occur)
UPDATE "cards" SET "swedish" = 'ske'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 623;

-- rank 628: Swedish cognate "förekomma" pins vorkommen (to occur/be present)
UPDATE "cards" SET "swedish" = 'förekomma'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 628;

-- rank 648: Swedish "genomföras" pins erfolgen (to take place/be carried out); the cognate "följa" drifted to mean "follow"
UPDATE "cards" SET "swedish" = 'genomföras'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 648;

-- rank 652: Swedish idiom "äga rum" pins stattfinden (to take place); "ta plats" is a false friend (= take up space)
UPDATE "cards" SET "swedish" = 'äga rum'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 652;

-- rank 654: Swedish cognate "uppträda" pins auftreten (to appear/occur/perform)
UPDATE "cards" SET "swedish" = 'uppträda'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 654;

-- rank 254: Swedish "olika" pins verschieden (various/different)
UPDATE "cards" SET "swedish" = 'olika'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 254;

-- rank 303: Swedish "annorlunda" pins anders (differently); the cognate "annars" is a false friend (= otherwise/else)
UPDATE "cards" SET "swedish" = 'annorlunda'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 303;

-- rank 345: Swedish "skilda" pins unterschiedlich (differing/distinct), mirroring Unterschied→skillnad
UPDATE "cards" SET "swedish" = 'skilda'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 345;

-- rank 240: Swedish cognate "doktor" pins Doktor (title/degree)
UPDATE "cards" SET "swedish" = 'doktor'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 240;

-- rank 622: Swedish "läkare" pins Arzt (physician/profession), vs. Doktor the title
UPDATE "cards" SET "swedish" = 'läkare'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 622;

-- rank 617: Swedish cognate "höja" pins erhöhen (to raise, transitive)
UPDATE "cards" SET "swedish" = 'höja'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 617;

-- rank 650: Swedish "tilltaga" pins zunehmen (to increase/grow, intransitive) — a morpheme-for-morpheme cognate (zu-nehmen = till-taga)
UPDATE "cards" SET "swedish" = 'tilltaga'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 650;
