-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 570: Swedish cognate "uppleva" pins erleben (to experience/live through) — er-leben = upp-leva
UPDATE "cards" SET "swedish" = 'uppleva'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 570;

-- rank 619: Swedish cognate "erfarenhet" pins Erfahrung (experience, noun)
UPDATE "cards" SET "swedish" = 'erfarenhet'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 619;

-- rank 690: Swedish cognate "erfara" pins erfahren (to experience/find out)
UPDATE "cards" SET "swedish" = 'erfara'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 690;

-- rank 552: Swedish cognate "viss" pins gewiss (certain/sure), vs. bestimmt→bestämd
UPDATE "cards" SET "swedish" = 'viss'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 552;
