-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 88: Swedish "eftersom" (subordinating because) pins weil, vs. denn
UPDATE "cards" SET "swedish" = 'eftersom'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 88;

-- rank 93: Swedish "ty" (coordinating for/because; colloq. "för") pins denn, vs. weil
UPDATE "cards" SET "swedish" = 'ty'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 93;

-- rank 429: Swedish cognate "nyttja" pins nutzen (utilize/make use of); Nutzen = nytta
UPDATE "cards" SET "swedish" = 'nyttja'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 429;

-- rank 538: Swedish "använda" pins verwenden (the general "use/employ")
UPDATE "cards" SET "swedish" = 'använda'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 538;

-- rank 1119: Swedish "begagna" pins benutzen (use/operate; cf. begagnad = used), vs. verwenden→använda
UPDATE "cards" SET "swedish" = 'begagna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1119;

-- rank 1258: Swedish "tillämpning" pins Anwendung (application; anwenden = tillämpa)
UPDATE "cards" SET "swedish" = 'tillämpning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1258;
