-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 275: scheinen carries both senses: "skina" (shine — the cognate, unique in this cluster) and "verka" (seem — its most frequent everyday use)
UPDATE "cards" SET "swedish" = 'skina, verka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 275;

-- rank 277: Swedish "se ut" pins aussehen (to look/appear) — aus-sehen = se ut
UPDATE "cards" SET "swedish" = 'se ut'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 277;

-- rank 408: Swedish "framträda" pins erscheinen (to appear/come forth/emerge)
UPDATE "cards" SET "swedish" = 'framträda'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 408;

-- rank 1228: Swedish "dyka upp" pins auftauchen (to surface/pop up) — auf-tauchen = dyka upp
UPDATE "cards" SET "swedish" = 'dyka upp'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1228;
