-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 780: Swedish cognate "insats" pins Einsatz (deployment/use/stake/effort) — in-satz = in-sats
UPDATE "cards" SET "swedish" = 'insats'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 780;

-- rank 1606: Swedish "användning" pins Verwendung (usage) — the noun of verwenden→använda
UPDATE "cards" SET "swedish" = 'användning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1606;

-- rank 2129: Swedish cognate "bruk" pins Gebrauch (use/usage) — ge-brauch ~ bruk
UPDATE "cards" SET "swedish" = 'bruk'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2129;

-- rank 2140: Swedish "nyttjande" pins Nutzung (usage/utilization) — the noun of nutzen→nyttja
UPDATE "cards" SET "swedish" = 'nyttjande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2140;

-- rank 2155: Swedish cognate "nytta" pins Nutzen (benefit/use/utility), the benefit sense
UPDATE "cards" SET "swedish" = 'nytta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2155;

-- rank 2831: Swedish cognate "bearbeta" pins verarbeiten (to process/work up) — ver-arbeiten ~ be-arbeta
UPDATE "cards" SET "swedish" = 'bearbeta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2831;

-- rank 3307: Swedish cognate "förbruka" pins verbrauchen (to consume/use up) — ver-brauchen ~ för-bruka
UPDATE "cards" SET "swedish" = 'förbruka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3307;

-- rank 4599: Swedish "utgift" pins Aufwendung (expense/expenditure) — the deck's "use" gloss is misleading
UPDATE "cards" SET "swedish" = 'utgift'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4599;

-- rank 135: Swedish cognate "ställa" pins stellen (put upright/vertical)
UPDATE "cards" SET "swedish" = 'ställa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 135;

-- rank 228: Swedish cognate "sätta" pins setzen (to set/put)
UPDATE "cards" SET "swedish" = 'sätta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 228;

-- rank 352: Swedish cognate "lägga" pins legen (to lay/put down, horizontal)
UPDATE "cards" SET "swedish" = 'lägga'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 352;

-- rank 688: Swedish "stoppa in" pins stecken (put/stick into); the cognate "sticka" drifted to prick/knit
UPDATE "cards" SET "swedish" = 'stoppa in'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 688;

-- rank 326: Swedish cognate "plats" pins Platz (place/room/square)
UPDATE "cards" SET "swedish" = 'plats'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 326;

-- rank 341: Swedish cognate "ort" pins Ort (place/locality/town)
UPDATE "cards" SET "swedish" = 'ort'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 341;

-- rank 344: Swedish cognate "ställe" pins Stelle (place/spot) — the noun to stellen/ställa
UPDATE "cards" SET "swedish" = 'ställe'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 344;

-- rank 151: Swedish cognate "egentligen" pins eigentlich (actually/strictly speaking)
UPDATE "cards" SET "swedish" = 'egentligen'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 151;

-- rank 685: Swedish cognate "äkta" pins echt (genuine/real)
UPDATE "cards" SET "swedish" = 'äkta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 685;

-- rank 1350: Swedish "reell" pins real (real/actual), vs. wirklich→verklig
UPDATE "cards" SET "swedish" = 'reell'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1350;

-- rank 208: Swedish cognate "arbete" pins Arbeit (work, noun)
UPDATE "cards" SET "swedish" = 'arbete'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 208;

-- rank 234: Swedish cognate "arbeta" pins arbeiten (to work)
UPDATE "cards" SET "swedish" = 'arbeta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 234;

-- rank 401: Swedish cognate "verka" pins wirken (to have an effect/act/work)
UPDATE "cards" SET "swedish" = 'verka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 401;

-- rank 677: Swedish cognate "fungera" pins funktionieren (to function/work)
UPDATE "cards" SET "swedish" = 'fungera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 677;

-- rank 681: Swedish cognate "verk" pins Werk (work/opus/plant)
UPDATE "cards" SET "swedish" = 'verk'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 681;

-- rank 191: Swedish cognate "nämna" pins nennen (to name/call/mention)
UPDATE "cards" SET "swedish" = 'nämna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 191;

-- rank 405: Swedish cognate "beteckna" pins bezeichnen (to designate/call as) — the als↔som construction matches: "als X bezeichnen" = "beteckna som X"
UPDATE "cards" SET "swedish" = 'beteckna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 405;

-- rank 530: Swedish cognate "ropa" pins rufen (to call out/shout) — rufen ~ ropa
UPDATE "cards" SET "swedish" = 'ropa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 530;

-- rank 1146: Swedish "ringa" pins anrufen (to call on the phone)
UPDATE "cards" SET "swedish" = 'ringa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1146;

-- rank 924: Swedish cognate "trycka" pins drücken (to press/push)
UPDATE "cards" SET "swedish" = 'trycka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 924;

-- rank 1221: Swedish cognate "stöta" pins stoßen (to bump/push) — stoßen ~ stöta
UPDATE "cards" SET "swedish" = 'stöta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1221;

-- rank 1251: Swedish cognate "skjuta (på)" pins schieben (to push/shove) — the "(på)" steers away from skjuta=shoot
UPDATE "cards" SET "swedish" = 'skjuta (på)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1251;

-- rank 1632: Swedish cognate "tränga" pins drängen (to push/press/urge) — drängen ~ tränga
UPDATE "cards" SET "swedish" = 'tränga'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1632;
