-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 2015: Swedish "öka" pins steigern (to boost/increase, transitive), vs. erhöhen→höja
UPDATE "cards" SET "swedish" = 'öka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2015;

-- rank 2074: Swedish "uppgång" pins Anstieg (a rise/increase, e.g. of prices)
UPDATE "cards" SET "swedish" = 'uppgång'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2074;

-- rank 2086: Swedish "höjning" pins Erhöhung (a raise/increase), the noun to erhöhen→höja
UPDATE "cards" SET "swedish" = 'höjning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2086;

-- rank 3147: Swedish cognate "förstora" pins vergrößern (to enlarge/increase in size) — ver+größer ~ för+stor
UPDATE "cards" SET "swedish" = 'förstora'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3147;

-- rank 3579: Swedish "ökning" pins Steigerung (an increase), the noun to steigern→öka
UPDATE "cards" SET "swedish" = 'ökning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3579;

-- rank 3788: Swedish "tillväxt" pins Zunahme (growth/increase), the noun to zunehmen→tilltaga
UPDATE "cards" SET "swedish" = 'tillväxt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3788;

-- rank 448: Swedish cognate "ändra" pins ändern (to change/alter)
UPDATE "cards" SET "swedish" = 'ändra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 448;

-- rank 500: Swedish cognate "förändra" pins verändern (to change/transform), vs. plain ändern→ändra
UPDATE "cards" SET "swedish" = 'förändra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 500;

-- rank 854: Swedish "förändring" pins Veränderung (change/transformation), the noun to verändern
UPDATE "cards" SET "swedish" = 'förändring'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 854;

-- rank 1084: Swedish cognate "växla" pins wechseln (to switch/swap/change) — wechseln ~ växla
UPDATE "cards" SET "swedish" = 'växla'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1084;

-- rank 1326: Swedish "ändring" pins Änderung (change/modification), the noun to ändern
UPDATE "cards" SET "swedish" = 'ändring'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1326;

-- rank 2513: Swedish "förvandling" pins Wandel (gradual change/transformation)
UPDATE "cards" SET "swedish" = 'förvandling'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2513;

-- rank 2525: Swedish "växling" pins Wechsel (switch/change), the noun to wechseln→växla
UPDATE "cards" SET "swedish" = 'växling'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2525;

-- rank 3169: Swedish cognate "omvandla" pins umwandeln (to convert/transform) — um- ~ om-
UPDATE "cards" SET "swedish" = 'omvandla'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3169;

-- rank 3225: Swedish "utjämning" pins Ausgleich (balancing/compensation) — steers away from "change"
UPDATE "cards" SET "swedish" = 'utjämning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3225;

-- rank 3647: Swedish cognate "byta" pins tauschen (to exchange/swap)
UPDATE "cards" SET "swedish" = 'byta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3647;

-- rank 3700: Swedish cognate "förvandla" pins wandeln (to change/transform)
UPDATE "cards" SET "swedish" = 'förvandla'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3700;

-- rank 450: Swedish cognate "lämna" pins verlassen (to leave/abandon a place)
UPDATE "cards" SET "swedish" = 'lämna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 450;

-- rank 1147: Swedish "avlägsna" pins entfernen (to remove; reflexive = leave/move away)
UPDATE "cards" SET "swedish" = 'avlägsna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1147;

-- rank 2291: Swedish "efterlämna" pins hinterlassen (to leave behind) — hinter- ~ efter-
UPDATE "cards" SET "swedish" = 'efterlämna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2291;

-- rank 2419: Swedish cognate "överlåta" pins überlassen (to leave/cede to someone) — über+lassen ~ över+låta
UPDATE "cards" SET "swedish" = 'överlåta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2419;

-- rank 2958: Swedish "bryta upp" pins aufbrechen — carries both senses (set off / break open) just like the German
UPDATE "cards" SET "swedish" = 'bryta upp'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2958;

-- rank 3144: Swedish "avgå" pins ausscheiden (to leave a post/retire/drop out), vs. austreten→utträda
UPDATE "cards" SET "swedish" = 'avgå'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3144;

-- rank 3655: Swedish "gå iväg" pins weggehen (to walk off/leave on foot), vs. losfahren→åka iväg
UPDATE "cards" SET "swedish" = 'gå iväg'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3655;

-- rank 4468: Swedish "åka iväg" pins losfahren (to drive off/depart by vehicle)
UPDATE "cards" SET "swedish" = 'åka iväg'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4468;

-- rank 4609: Swedish cognate "utträda" pins austreten (to resign/leave an organization) — aus+treten ~ ut+träda
UPDATE "cards" SET "swedish" = 'utträda'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4609;

-- rank 4690: Swedish "gå av" pins abgehen (to come off/go off) — ab+gehen ~ av+gå
UPDATE "cards" SET "swedish" = 'gå av'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4690;

-- rank 8: Swedish cognate "bli" pins werden (to become) — the become-sense of "get", vs. bekommen=receive
UPDATE "cards" SET "swedish" = 'bli'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 8;

-- rank 212: Swedish "få" pins bekommen (to get/receive) — note: bekommen ≠ become (=werden)
UPDATE "cards" SET "swedish" = 'få'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 212;

-- rank 547: Swedish cognate "hämta" pins holen (to fetch/go get)
UPDATE "cards" SET "swedish" = 'hämta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 547;

-- rank 724: Swedish "få (vardagligt)" pins kriegen — the colloquial twin of bekommen, same word in Swedish
UPDATE "cards" SET "swedish" = 'få (vardagligt)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 724;

-- rank 878: Swedish "hänvisa till" pins beziehen via its dominant "sich ~ auf = refer to" sense (the "get" gloss is marginal)
UPDATE "cards" SET "swedish" = 'hänvisa till (sich ~ auf)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 878;

-- rank 2377: Swedish "hämta upp" pins abholen (to pick up/collect), vs. plain holen→hämta
UPDATE "cards" SET "swedish" = 'hämta upp'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2377;

-- rank 3653: Swedish "få med sig" pins mitbekommen (to catch/notice/pick up on) — mit+bekommen ~ få med sig
UPDATE "cards" SET "swedish" = 'få med sig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3653;

-- rank 3839: Swedish "skaffa sig" pins zulegen (sich etwas ~ = get/acquire for oneself)
UPDATE "cards" SET "swedish" = 'skaffa sig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3839;

-- rank 4170: Swedish "skaffa" pins besorgen (to get/procure/provide), vs. reflexive zulegen→skaffa sig
UPDATE "cards" SET "swedish" = 'skaffa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4170;

-- rank 155: Swedish "hålla, stanna" pins halten: hålla (hold — dominant sense, e.g. håll boken / hålla ett tal) + stanna (stop, of a vehicle: bussen stannar)
UPDATE "cards" SET "swedish" = 'hålla, stanna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 155;

-- rank 995: Swedish "sluta" pins aufhören (to stop/cease an activity)
UPDATE "cards" SET "swedish" = 'sluta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 995;

-- rank 1085: Swedish calque "ställa in" pins einstellen (adjust/set; also cancel/discontinue) — many-sensed (employ = anställa)
UPDATE "cards" SET "swedish" = 'ställa in'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1085;

-- rank 1620: Swedish "stanna" pins anhalten (to come to a stop/halt)
UPDATE "cards" SET "swedish" = 'stanna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1620;

-- rank 2132: Swedish cognate "uppehålla" pins aufhalten (to hold up/delay; sich ~ = stay) — auf+halten ~ uppe+hålla
UPDATE "cards" SET "swedish" = 'uppehålla'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2132;

-- rank 2249: Swedish cognate "stoppa" pins stoppen (to stop)
UPDATE "cards" SET "swedish" = 'stoppa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2249;

-- rank 2562: Swedish "hållplats" pins Station in its "stop on a route" sense (vs. abstract stop verbs)
UPDATE "cards" SET "swedish" = 'hållplats'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2562;

-- rank 2823: Swedish cognate "avbryta" pins abbrechen (to break off/abort) — ab+brechen ~ av+bryta
UPDATE "cards" SET "swedish" = 'avbryta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2823;

-- rank 4388: Swedish cognate "halt" pins Halt (a stop/halt: göra halt); support-sense = stöd
UPDATE "cards" SET "swedish" = 'halt, stöd'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4388;

-- rank 413: Swedish "resultera i" pins ergeben (to result in/yield), vs. the actual make-verbs
UPDATE "cards" SET "swedish" = 'resultera i'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 413;

-- rank 1000: Swedish cognate "producera" pins produzieren (to produce)
UPDATE "cards" SET "swedish" = 'producera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1000;

-- rank 1046: Swedish "tillverka" pins herstellen (to manufacture/make)
UPDATE "cards" SET "swedish" = 'tillverka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1046;

-- rank 1330: Swedish "alstra" pins erzeugen (to generate — energy/heat: alstra el/värme), vs. herstellen→tillverka
UPDATE "cards" SET "swedish" = 'alstra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1330;

-- rank 2383: Swedish calque "lägga fram" pins vorlegen (to present/submit) — vor+legen ~ fram+lägga
UPDATE "cards" SET "swedish" = 'lägga fram'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2383;

-- rank 2389: Swedish "upprätta" pins erstellen (to draw up/create a document: upprätta ett avtal)
UPDATE "cards" SET "swedish" = 'upprätta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2389;

-- rank 3668: Swedish "prestera" pins erbringen (to render/produce: eine Leistung erbringen = prestera)
UPDATE "cards" SET "swedish" = 'prestera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3668;

-- rank 4562: Swedish cognate "frambringa" pins hervorbringen (to bring forth) — hervor+bringen ~ fram+bringa
UPDATE "cards" SET "swedish" = 'frambringa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4562;

-- rank 4999: Swedish "framställa" pins fertigen (to manufacture); cognate förfärdiga (fertigen ~ förfärdiga)
UPDATE "cards" SET "swedish" = 'framställa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4999;
