-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 119: Swedish cognate "därmed" pins damit (with it/thereby) — da+mit = där+med
UPDATE "cards" SET "swedish" = 'därmed'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 119;

-- rank 129: Swedish "därvid" pins dabei (thereby/at that); the presence sense "dabei sein" = vara med
UPDATE "cards" SET "swedish" = 'därvid, med'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 129;

-- rank 150: Swedish cognate "därtill" pins dazu (in addition/to that) — da+zu = där+till
UPDATE "cards" SET "swedish" = 'därtill'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 150;

-- rank 175: FALSE FRIEND: dafür = "for it/in favor" = Swedish "för det", NOT "därför" (which means therefore). The gloss carries the warning so it is learned, not hidden
UPDATE "cards" SET "swedish" = 'för det (≠ därför)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 175;

-- rank 195: Swedish cognate "därpå" pins darauf (on it/thereupon) — da(r)+auf = där+på
UPDATE "cards" SET "swedish" = 'därpå'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 195;

-- rank 214: Swedish cognate "därav" pins davon (thereof/from it) — da+von = där+av
UPDATE "cards" SET "swedish" = 'därav'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 214;

-- rank 283: Swedish "däröver" (above it) / "därom" (about it) pin darüber — da(r)+über = där+över
UPDATE "cards" SET "swedish" = 'däröver, därom'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 283;

-- rank 286: damals = "back then/at that time" (past-time adverb, NOT a där-compound) = Swedish "då, på den tiden"
UPDATE "cards" SET "swedish" = 'då, på den tiden'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 286;

-- rank 292: daran (on/at it) has no clean där-form (an → på/vid) = Swedish "på det, vid det", vs. darauf→därpå
UPDATE "cards" SET "swedish" = 'på det, vid det'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 292;

-- rank 354: daher = "därför" (therefore — here the där-word IS right, unlike dafür) + "därifrån" (from there)
UPDATE "cards" SET "swedish" = 'därför, därifrån'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 354;

-- rank 360: Swedish cognate "däri" (therein) / "därinne" (in there) pin darin — da(r)+in = där+i
UPDATE "cards" SET "swedish" = 'däri, därinne'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 360;

-- rank 374: The CONJUNCTION damit (so that/in order that) — homograph of rank-119 damit (with it) — = Swedish "för att, så att"
UPDATE "cards" SET "swedish" = 'för att, så att'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 374;

-- rank 457: Swedish cognate "därefter" (thereafter) / "efteråt" (afterwards) pin danach — da+nach = där+efter
UPDATE "cards" SET "swedish" = 'därefter, efteråt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 457;

-- rank 466: Swedish cognate "därigenom" pins dadurch (through it/as a result) — da+durch = där+igenom
UPDATE "cards" SET "swedish" = 'därigenom'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 466;

-- rank 467: Swedish cognate "däremot" pins dagegen (against it/on the other hand) — da+gegen = där+emot
UPDATE "cards" SET "swedish" = 'däremot'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 467;

-- rank 518: darum = "därför" (therefore) + "runt det" (physically around it) — da+rum = där+om/runt
UPDATE "cards" SET "swedish" = 'därför, runt det'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 518;

-- rank 1026: Swedish cognate "därunder" pins darunter (under it/among them) — da(r)+unter = där+under
UPDATE "cards" SET "swedish" = 'därunder'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1026;
