-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 454: endlich = the relief "at last" — Swedish "äntligen" (not the "eventually" of schließlich)
UPDATE "cards" SET "swedish" = 'äntligen'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 454;

-- rank 351: schließlich = "eventually / in the end / after all" — Swedish "slutligen, till slut"
UPDATE "cards" SET "swedish" = 'slutligen, till slut'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 351;

-- rank 1485: ausschließlich = "solely, exclusively" — Swedish cognate "uteslutande" (aus-schließen → ute-sluta)
UPDATE "cards" SET "swedish" = 'uteslutande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1485;

-- rank 661: wesentlich (essential, substantial) — clean Swedish cognate "väsentlig", senses line up
UPDATE "cards" SET "swedish" = 'väsentlig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 661;

-- rank 416: betreffen (to concern/affect) — modern everyday "angå" (det angår mig), not the stilted cognate "beträffa" (only alive in "vad beträffar")
UPDATE "cards" SET "swedish" = 'angå'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 416;

-- rank 424: außerdem (besides, in addition) — everyday Swedish "dessutom" (des-utom ≈ außer-dem)
UPDATE "cards" SET "swedish" = 'dessutom'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 424;

-- rank 542: zudem (moreover, furthermore) — more formal register, Swedish "därtill"
UPDATE "cards" SET "swedish" = 'därtill'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 542;

-- rank 649: Beziehung (relation, connection) — Swedish "relation"
UPDATE "cards" SET "swedish" = 'relation'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 649;

-- rank 668: Verhältnis (relationship; also ratio/proportion) — cognate "förhållande" (ver-hält-nis ≈ för-håll-ande)
UPDATE "cards" SET "swedish" = 'förhållande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 668;

-- rank 912: Bindung (emotional bond/attachment) — everyday "anknytning, band"; avoid the cognate "bindning" (technical: chemical/ski/book binding)
UPDATE "cards" SET "swedish" = 'anknytning, band'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 912;

-- rank 3577: Relation (formal: proportion, ratio) — Swedish "proportion, samband", kept distinct from Beziehung → relation
UPDATE "cards" SET "swedish" = 'proportion, samband'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3577;

-- rank 555: Lage (situation, location, position) — cognate "läge"
UPDATE "cards" SET "swedish" = 'läge'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 555;

-- rank 423: Situation — the loanword, identical Swedish "situation"; glossed to complete the Lage/Situation split
UPDATE "cards" SET "swedish" = 'situation'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 423;

-- rank 1061: existieren (to exist) — loanword "existera"
UPDATE "cards" SET "swedish" = 'existera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1061;

-- rank 246: bestehen — cognate "bestå" covers consist of / persist / pass (an exam); the "insist" sense (bestehen auf) is separate (insistera på)
UPDATE "cards" SET "swedish" = 'bestå'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 246;

-- rank 647: vorliegen (to be at hand/present, exist) — cognate "föreligga" (vor-liegen ≈ före-ligga); formal but current, everyday alt "finnas"
UPDATE "cards" SET "swedish" = 'föreligga'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 647;

-- rank 196: eben — temporal "just now" (han gick nyss) + the "exactly" sense; Swedish "nyss, just"
UPDATE "cards" SET "swedish" = 'nyss, just'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 196;

-- rank 478: halt — modal particle "simply / that's just how it is" (det är helt enkelt så); Swedish "helt enkelt"
UPDATE "cards" SET "swedish" = 'helt enkelt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 478;

-- rank 114: nun (now; discourse "well then") — Swedish "nu, nå"
UPDATE "cards" SET "swedish" = 'nu, nå'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 114;

-- rank 72: jetzt — the plain concrete "now", Swedish "nu"
UPDATE "cards" SET "swedish" = 'nu'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 72;

-- rank 4228: nunmehr (now, by now, henceforth) — cognate "numera" (nun-mehr ≈ nu-mera)
UPDATE "cards" SET "swedish" = 'numera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4228;

-- rank 672: beispielsweise (for example) — clean structural match "exempelvis" (Beispiel-s-weise ≈ exempel-vis)
UPDATE "cards" SET "swedish" = 'exempelvis'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 672;

-- rank 258: entsprechen (to correspond to, match) — Swedish "motsvara" (etwas entspricht ≈ motsvara något)
UPDATE "cards" SET "swedish" = 'motsvara'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 258;

-- rank 510: schauen (to look) — general everyday "titta"
UPDATE "cards" SET "swedish" = 'titta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 510;

-- rank 507: ansehen (to look at, watch) — "titta på, se på" (≈ anschauen, genuine synonym)
UPDATE "cards" SET "swedish" = 'titta på, se på'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 507;

-- rank 949: anschauen (to look at, watch) — South-German ≈ ansehen; "titta på"
UPDATE "cards" SET "swedish" = 'titta på'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 949;

-- rank 485: betrachten (to look at, consider) — cognate "betrakta" (the considered regard/contemplate)
UPDATE "cards" SET "swedish" = 'betrakta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 485;

-- rank 1256: blicken (to look, glance) — cognate "blicka"
UPDATE "cards" SET "swedish" = 'blicka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1256;

-- rank 306: Blick (noun: look, glance, gaze) — Swedish "blick"
UPDATE "cards" SET "swedish" = 'blick'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 306;

-- rank 1362: gucken (to look) — colloquial "kika, kolla"
UPDATE "cards" SET "swedish" = 'kika, kolla'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1362;

-- rank 3078: angucken (to look at) — colloquial "kolla på, kika på"
UPDATE "cards" SET "swedish" = 'kolla på, kika på'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3078;

-- rank 293: suchen (to search, look for) — "söka, leta"
UPDATE "cards" SET "swedish" = 'söka, leta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 293;

-- rank 1944: versorgen (to supply, provide, look after) — cognate "försörja" (ver-sorgen ≈ för-sörja) + "ta hand om"
UPDATE "cards" SET "swedish" = 'försörja, ta hand om'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1944;

-- rank 3123: betreuen (to look after, take care, supervise) — "ta hand om, sköta"
UPDATE "cards" SET "swedish" = 'ta hand om, sköta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3123;

-- rank 1540: vorsehen (to plan, earmark, provide for; sich vorsehen = watch out) — "planera, avse; akta sig"
UPDATE "cards" SET "swedish" = 'planera, avse; akta sig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1540;
