-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 270: besonders (adverb: particularly, especially) — "särskilt"
UPDATE "cards" SET "swedish" = 'särskilt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 270;

-- rank 512: besondere (adjective: special) — "särskild"
UPDATE "cards" SET "swedish" = 'särskild'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 512;

-- rank 655: insbesondere (in particular, especially) — "i synnerhet" (keeps it distinct from besonders = särskilt)
UPDATE "cards" SET "swedish" = 'i synnerhet'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 655;
