-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 115: sondern is the not-X-but-Y "but" (Swedish "utan"); the old example glossed an aber-style clause contrast ("...but his sister does") and had awkward German word order — replaced with a proper not-X-but-Y pair, plus the Swedish gloss
UPDATE "cards" SET "swedish" = 'utan', "example_en" = 'It''s not him but his sister who likes soccer.', "example_de" = 'Nicht er, sondern seine Schwester mag Fußball.'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 115;
