-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 221: the "weiter" example used "weitere" (the rank-182 card), never the word itself — replaced with a sentence in the adverbial "onwards" sense (first shipped as 0012); Swedish "vidare" splits it from weitere→ytterligare, the same confusion the example fix was for
UPDATE "cards" SET "swedish" = 'vidare', "example_en" = 'We’re tired, but we walk a little further.', "example_de" = 'Wir sind müde, aber wir gehen noch ein bisschen weiter.'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 221;

-- rank 73: Swedish cognate "dock" pins doch (however/but) — literally the same word; leaves "men" to aber
UPDATE "cards" SET "swedish" = 'dock'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 73;

-- rank 227: Swedish "emellertid" pins jedoch (however) in the same written register, keeping it distinct from doch→dock
UPDATE "cards" SET "swedish" = 'emellertid'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 227;

-- rank 31: Swedish "men" pins aber as the default "but" — the anchor that makes doch→dock informative, since English calls both "but"
UPDATE "cards" SET "swedish" = 'men'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 31;

-- rank 206: zwar has two uses and the prompt names both: zwar…aber = "visserligen", und zwar = "närmare bestämt" (the sense the example tests)
UPDATE "cards" SET "swedish" = 'visserligen / närmare bestämt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 206;

-- rank 225: Swedish "minsann" carries the emphatic, I-grant-you-that sense of allerdings that the example tests (Das ist allerdings… = Det är minsann…)
UPDATE "cards" SET "swedish" = 'minsann, verkligen'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 225;

-- rank 390: Swedish "fastän" pins obwohl — same subordinating conjunction; the full form over bare "fast" keeps it unmistakably the conjunction
UPDATE "cards" SET "swedish" = 'fastän'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 390;

-- rank 717: Swedish "ändå" pins dennoch (nevertheless) and leaves "trots det" to trotzdem (463), the card it would otherwise be confused with
UPDATE "cards" SET "swedish" = 'ändå'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 717;

-- rank 1016: Swedish "å andra sidan" pins hingegen; the literal match "däremot" is already on dagegen (467), so this keeps the two apart
UPDATE "cards" SET "swedish" = 'å andra sidan'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1016;

-- rank 182: Swedish "ytterligare" pins weitere (additional/further, attributive) — Weitere Informationen = Ytterligare information; weiter (221) takes "vidare"
UPDATE "cards" SET "swedish" = 'ytterligare'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 182;

-- rank 583: Swedish "extra, kompletterande" pins zusätzlich (additional), keeping it distinct from weitere→ytterligare
UPDATE "cards" SET "swedish" = 'extra, kompletterande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 583;

-- rank 827: Swedish "vidare, fortfarande" pins weiterhin — both its senses (going forward / still), matching its example "Es gibt weiterhin Probleme" = "Det finns fortfarande problem"
UPDATE "cards" SET "swedish" = 'vidare, fortfarande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 827;

-- rank 604: Swedish cognate "minst" pins mindestens as the numerical floor (mindestens acht Stunden = minst åtta timmar), vs. zumindest→åtminstone
UPDATE "cards" SET "swedish" = 'minst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 604;

-- rank 612: Swedish "åtminstone" pins zumindest as the concessive "at least" (aber zumindest habe ich es versucht), vs. mindestens→minst
UPDATE "cards" SET "swedish" = 'åtminstone'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 612;

-- rank 1138: Swedish "i alla fall" pins wenigstens (at least, if nothing else), keeping "åtminstone" on zumindest
UPDATE "cards" SET "swedish" = 'i alla fall'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1138;

-- rank 2362: Swedish cognate "högst" pins höchstens (at most) — the mirror of mindestens→minst
UPDATE "cards" SET "swedish" = 'högst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2362;

-- rank 676: Swedish "för närvarande" pins derzeit (adverb: at the moment), mirroring derzeitig→nuvarande
UPDATE "cards" SET "swedish" = 'för närvarande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 676;

-- rank 4459: Swedish "nuvarande" pins derzeitig (adjective: current) — die derzeitige Situation = den nuvarande situationen
UPDATE "cards" SET "swedish" = 'nuvarande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4459;

-- rank 3014: Swedish "just nu" pins zurzeit as the everyday "at the moment", distinct from derzeit→för närvarande
UPDATE "cards" SET "swedish" = 'just nu'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3014;

-- rank 2661: Swedish "för tillfället" pins momentan (at the moment), distinct from derzeit and zurzeit
UPDATE "cards" SET "swedish" = 'för tillfället'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2661;

-- rank 2378: Swedish "rådande" pins gegenwärtig (present/current) — die gegenwärtige politische Lage = den rådande politiska situationen; keeps "nuvarande" on derzeitig
UPDATE "cards" SET "swedish" = 'rådande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2378;

-- rank 534: inzwischen carries both senses and its prompt is "in the meantime", so the gloss leads with "under tiden" and keeps "numera" for the by-now use its example shows
UPDATE "cards" SET "swedish" = 'under tiden, numera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 534;

-- rank 862: Swedish "vid det här laget" pins mittlerweile as the by-this-point sense (Mittlerweile haben alle Dörfer Internet)
UPDATE "cards" SET "swedish" = 'vid det här laget'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 862;

-- rank 4617: Swedish "samtidigt" pins unterdessen as pure simultaneity (ich koche unterdessen das Abendessen), leaving "under tiden" to inzwischen
UPDATE "cards" SET "swedish" = 'samtidigt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4617;

-- rank 3162: Swedish "när som helst" pins jederzeit (anytime) exactly
UPDATE "cards" SET "swedish" = 'när som helst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3162;

-- rank 193: Swedish cognate "dra" pins ziehen — the root that makes the whole compound family legible
UPDATE "cards" SET "swedish" = 'dra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 193;

-- rank 4348: Swedish "föredra" is vorziehen morpheme-for-morpheme (vor+ziehen = före+dra), which English "prefer" hides completely
UPDATE "cards" SET "swedish" = 'föredra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4348;

-- rank 3796: Swedish "dra av" is abziehen morpheme-for-morpheme (ab = av); the example is the subtract sense
UPDATE "cards" SET "swedish" = 'dra av'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3796;

-- rank 2111: Swedish "dra sig tillbaka" is zurückziehen morpheme-for-morpheme (zurück = tillbaka), reflexive like the example
UPDATE "cards" SET "swedish" = 'dra sig tillbaka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2111;

-- rank 1436: anziehen spans attract and put-on, so the gloss carries both: "dra till sig" (the example) and "ta på sig"
UPDATE "cards" SET "swedish" = 'dra till sig; ta på sig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1436;

-- rank 3870: überziehen spans put-on (its example) and the banking overdraw, so the gloss carries both Swedish words
UPDATE "cards" SET "swedish" = 'dra på sig; övertrassera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3870;

-- rank 4854: aufziehen spans rear (its example) and wind-up; "uppfostra; dra upp" carries both, with auf = upp visible in the second
UPDATE "cards" SET "swedish" = 'uppfostra; dra upp'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4854;

-- rank 2973: Swedish "dra ut ur, frånta" pins entziehen — Salz entzieht dem Körper Wasser = saltet drar ut vatten ur kroppen
UPDATE "cards" SET "swedish" = 'dra ut ur, frånta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2973;

-- rank 2434: ausziehen spans move-out (its example) and take-off-clothes; Swedish uses neither dra- compound, hence "flytta ut; ta av sig"
UPDATE "cards" SET "swedish" = 'flytta ut; ta av sig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2434;

-- rank 2665: Swedish "flytta in" pins einziehen (to move in) — no dra- compound, unlike most of the family
UPDATE "cards" SET "swedish" = 'flytta in'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2665;

-- rank 3190: Swedish "involvera, räkna in" pins einbeziehen (to include/involve), matching its example about involving the children
UPDATE "cards" SET "swedish" = 'involvera, räkna in'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3190;

-- rank 3968: Swedish "förstå, sätta sig in i" pins nachvollziehen (to understand/relate to) — the empathetic understanding its example shows
UPDATE "cards" SET "swedish" = 'förstå, sätta sig in i'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3968;

-- rank 3782: Swedish "anlita, ta hjälp av" pins heranziehen in the consult-a-source sense its example uses
UPDATE "cards" SET "swedish" = 'anlita, ta hjälp av'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3782;

-- rank 4119: Swedish "förvrida (munnen)" pins verziehen (to distort/twist), matching its pucker-the-mouth example
UPDATE "cards" SET "swedish" = 'förvrida (munnen)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4119;

-- rank 3975: Swedish "fullfölja" pins durchziehen (see it through); the obvious "genomföra" is avoided because erfolgen (648) already holds "genomföras"
UPDATE "cards" SET "swedish" = 'fullfölja'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3975;

-- rank 3436: vollziehen spans transitive carry-out and reflexive take-place (its example is the latter), so the gloss carries both; "äga rum" was unavailable — it is on stattfinden (652)
UPDATE "cards" SET "swedish" = 'verkställa; (sich ~) ske'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3436;

-- rank 561: Swedish "röra (sig)" pins bewegen as moving oneself, reflexive like its example — distinct from ziehen→dra
UPDATE "cards" SET "swedish" = 'röra (sig)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 561;

-- rank 48: Swedish "där" pins da as the neutral location "there", the anchor of the där/dit grid
UPDATE "cards" SET "swedish" = 'där'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 48;

-- rank 139: Swedish "där borta" pins dort as the distal location "there" — its own example is "dort drüben"
UPDATE "cards" SET "swedish" = 'där borta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 139;

-- rank 1520: Swedish "dit" pins dahin as motion-toward-there; dit vs. där is exactly dahin vs. da, a split English cannot express
UPDATE "cards" SET "swedish" = 'dit'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1520;

-- rank 2599: Swedish "dit bort" pins dorthin as distal motion-toward, completing the där/där borta/dit/dit bort grid
UPDATE "cards" SET "swedish" = 'dit bort'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2599;

-- rank 712: Swedish "dit, bort" pins hin as the direction-away marker the whole -hin column is built from
UPDATE "cards" SET "swedish" = 'dit, bort'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 712;

-- rank 2457: Swedish "gå dit" is hingehen morpheme-for-morpheme (hin+gehen = dit+gå)
UPDATE "cards" SET "swedish" = 'gå dit'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2457;

-- rank 4881: Swedish "åka dit" is hinfahren morpheme-for-morpheme, same construction as hingehen→gå dit
UPDATE "cards" SET "swedish" = 'åka dit'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4881;

-- rank 2792: dastehen spans literal standing-there and the figurative be-in-a-position its example uses (steht gut da = står sig bra), so the gloss carries both
UPDATE "cards" SET "swedish" = 'stå där; stå sig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2792;

-- rank 2938: Swedish "på andra sidan" pins drüben as the other-side word it literally is; "där borta" is spent on dort (139)
UPDATE "cards" SET "swedish" = 'på andra sidan'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2938;

-- rank 417: Swedish "uppe, ovanpå" pins oben as the static "up there" — uppe/upp mirrors the same location/motion split as där/dit
UPDATE "cards" SET "swedish" = 'uppe, ovanpå'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 417;

-- rank 229: Swedish "därför" pins deshalb as the plain default "therefore"
UPDATE "cards" SET "swedish" = 'därför'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 229;

-- rank 749: deswegen is interchangeable with deshalb, so it also leads with "därför"; the parenthetical exposes wegen = orsak to tell the two cards apart
UPDATE "cards" SET "swedish" = 'därför (av den orsaken)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 749;

-- rank 792: Swedish "alltså, därmed" pins somit (consequently/thus), leading with alltså to keep it off damit→därmed (119)
UPDATE "cards" SET "swedish" = 'alltså, därmed'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 792;

-- rank 1227: Swedish "följaktligen" pins demnach as the inferential "therefore" (Es gibt demnach nur zwei Möglichkeiten)
UPDATE "cards" SET "swedish" = 'följaktligen'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1227;

-- rank 1815: Swedish "såtillvida, i den mån" pins insofern as "to that extent", its actual meaning behind the English "therefore"
UPDATE "cards" SET "swedish" = 'såtillvida, i den mån'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1815;

-- rank 684: Swedish cognate "tjäna" pins dienen (to serve) — the root of the tjäna/förtjäna/betjäna set
UPDATE "cards" SET "swedish" = 'tjäna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 684;

-- rank 835: verdienen = förtjäna by prefix, but its example is earning money and Swedish says "tjäna pengar" (förtjäna has drifted to "deserve"), so the gloss carries both
UPDATE "cards" SET "swedish" = 'förtjäna; tjäna (pengar)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 835;

-- rank 2179: bedienen = betjäna by prefix, but its example is operating a machine and "betjäna en maskin" is not idiomatic Swedish — hence "sköta (maskin)" alongside
UPDATE "cards" SET "swedish" = 'betjäna; sköta (maskin)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2179;

-- rank 1558: Swedish cognate "tjänst" pins der Dienst (service/duty), the noun side of dienen→tjäna
UPDATE "cards" SET "swedish" = 'tjänst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1558;

-- rank 2305: Swedish "tjänst, service" pins die Dienstleistung (a service, commercial sense)
UPDATE "cards" SET "swedish" = 'tjänst, service'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2305;

-- rank 4476: Swedish cognate "tjänare" pins der Diener (servant), completing the dien-/tjän- root family
UPDATE "cards" SET "swedish" = 'tjänare'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4476;

-- rank 79: Swedish cognate "se" pins sehen — the root of the whole ansehen/zusehen/Zuschauer family
UPDATE "cards" SET "swedish" = 'se'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 79;

-- rank 348: Swedish "klocka" covers all three senses of die Uhr at once (clock, wristwatch, klockan 3 = um 3 Uhr) exactly as German does; only English needs three words
UPDATE "cards" SET "swedish" = 'klocka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 348;

-- rank 4180: Swedish "övervaka" is überwachen morpheme-for-morpheme (über+wachen = över+vaka) and is the live surveillance word its example uses
UPDATE "cards" SET "swedish" = 'övervaka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4180;

-- rank 697: Swedish "iaktta, observera" pins beobachten — beobachtet seine Kinder = iakttar sina barn
UPDATE "cards" SET "swedish" = 'iaktta, observera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 697;

-- rank 2182: what separates zusehen from ansehen is grammar, not the Swedish verb: dative + an activity, so the gloss spells out "se på (ngn göra ngt)"
UPDATE "cards" SET "swedish" = 'se på (ngn göra ngt)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2182;

-- rank 3239: zuschauen is the -schauen twin of zusehen, so it takes "titta på" like anschauen does, with the same dative-activity note
UPDATE "cards" SET "swedish" = 'titta på (ngn göra ngt)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3239;

-- rank 1410: Swedish "åskådare" pins der Zuschauer (spectator), the noun to zuschauen
UPDATE "cards" SET "swedish" = 'åskådare'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1410;

-- rank 533: Swedish "tillsammans" pins zusammen (together), the root of the whole samman-/ihop family
UPDATE "cards" SET "swedish" = 'tillsammans'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 533;

-- rank 525: Swedish cognate "sammanhang" pins der Zusammenhang and covers both its senses (connection and context) exactly as the German does
UPDATE "cards" SET "swedish" = 'sammanhang'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 525;

-- rank 1312: Swedish cognate "samarbete" pins die Zusammenarbeit (cooperation)
UPDATE "cards" SET "swedish" = 'samarbete'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1312;

-- rank 2747: Swedish cognate "samarbeta" pins zusammenarbeiten, the verb to Zusammenarbeit→samarbete
UPDATE "cards" SET "swedish" = 'samarbeta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2747;

-- rank 1858: Swedish "sammanfatta" is zusammenfassen morpheme-for-morpheme (zusammen+fassen = samman+fatta)
UPDATE "cards" SET "swedish" = 'sammanfatta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1858;

-- rank 3001: Swedish cognate "sammanfattning" pins die Zusammenfassung, the noun to zusammenfassen→sammanfatta
UPDATE "cards" SET "swedish" = 'sammanfattning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3001;

-- rank 3110: Swedish cognate "sammansättning" pins die Zusammensetzung — the noun keeps samman- where the verb (2881) goes to "sätta ihop"
UPDATE "cards" SET "swedish" = 'sammansättning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3110;

-- rank 4956: Swedish everyday "hålla ihop" pins zusammenhalten (the cognate "sammanhålla" is stiff), matching its stick-together-as-siblings example
UPDATE "cards" SET "swedish" = 'hålla ihop'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4956;

-- rank 2710: Swedish everyday "hänga ihop (med)" pins zusammenhängen; "sammanhänga" exists but is not said
UPDATE "cards" SET "swedish" = 'hänga ihop (med)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2710;

-- rank 2881: Swedish "sätta ihop" pins zusammensetzen — the physical verb takes ihop even though its noun stays sammansättning (3110)
UPDATE "cards" SET "swedish" = 'sätta ihop'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2881;

-- rank 3633: Swedish "samlas, träffas" pins zusammenkommen (to come together), matching its whole-family-at-Christmas example
UPDATE "cards" SET "swedish" = 'samlas, träffas'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3633;

-- rank 3648: Swedish "leva tillsammans" pins zusammenleben, built straight off zusammen→tillsammans
UPDATE "cards" SET "swedish" = 'leva tillsammans'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3648;

-- rank 4730: zusammenbrechen leads with "bryta samman" to keep the samman- pattern visible, plus "rasa" for the collapsing-bridge sense its example uses
UPDATE "cards" SET "swedish" = 'bryta samman, rasa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4730;

-- rank 1821: Swedish "varandra" pins einander — the root that makes every PREP+einander card readable
UPDATE "cards" SET "swedish" = 'varandra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1821;

-- rank 716: miteinander = med varandra, the preposition riding in front exactly as in German
UPDATE "cards" SET "swedish" = 'med varandra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 716;

-- rank 1883: voneinander = av varandra (viel voneinander lernen = lära sig mycket av varandra)
UPDATE "cards" SET "swedish" = 'av varandra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1883;

-- rank 4085: zueinander = till varandra (müssen zueinander passen = måste passa till varandra)
UPDATE "cards" SET "swedish" = 'till varandra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4085;

-- rank 3269: aufeinander = på varandra (leg die Bücher aufeinander = lägg böckerna på varandra)
UPDATE "cards" SET "swedish" = 'på varandra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3269;

-- rank 4440: nebeneinander = bredvid varandra, morpheme-for-morpheme (neben = bredvid)
UPDATE "cards" SET "swedish" = 'bredvid varandra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4440;

-- rank 3295: untereinander breaks the pattern: Swedish has the dedicated "sinsemellan", not "under varandra"
UPDATE "cards" SET "swedish" = 'sinsemellan'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3295;

-- rank 1755: gegenseitig is the adjective, not a varandra phrase — Swedish "ömsesidig" matches its register
UPDATE "cards" SET "swedish" = 'ömsesidig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1755;

-- rank 1841: die Auseinandersetzung is aus-einander-setzen literally but means a quarrel; Swedish "gräl, dispyt" says so
UPDATE "cards" SET "swedish" = 'gräl, dispyt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1841;

-- rank 3841: Swedish "ta itu med, bearbeta" pins auseinandersetzen (to deal with), matching its therapy example; "sätta sig in i" is spent on nachvollziehen (3968)
UPDATE "cards" SET "swedish" = 'ta itu med, bearbeta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3841;

-- rank 736: Swedish "tillstånd" is der Zustand morpheme-for-morpheme (zu+stand = till+stånd) — how something IS, vs. Bedingung→villkor
UPDATE "cards" SET "swedish" = 'tillstånd'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 736;

-- rank 673: Swedish "villkor" pins die Bedingung as what is REQUIRED; English calls both this and Zustand a "condition", Swedish does not
UPDATE "cards" SET "swedish" = 'villkor'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 673;

-- rank 703: Swedish "föreläsning" is die Vorlesung morpheme-for-morpheme (vor+lesung = före+läsning)
UPDATE "cards" SET "swedish" = 'föreläsning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 703;

-- rank 2879: Swedish "föredrag" is der Vortrag morpheme-for-morpheme (vor+trag = före+drag); English calls both this and Vorlesung a "lecture"
UPDATE "cards" SET "swedish" = 'föredrag'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2879;

-- rank 3690: vorlesen is a false friend: Swedish "föreläsa" means to lecture, not to read aloud — hence "läsa högt (för)"
UPDATE "cards" SET "swedish" = 'läsa högt (för)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3690;

-- rank 756: Swedish "överallt" is überall morpheme-for-morpheme (über+all = över+allt)
UPDATE "cards" SET "swedish" = 'överallt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 756;

-- rank 935: Swedish "någonstans" pins irgendwo (somewhere), completing the överallt/någonstans/ingenstans row
UPDATE "cards" SET "swedish" = 'någonstans'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 935;

-- rank 3806: Swedish "ingenstans" pins nirgendwo (nowhere); nirgends (4577) is a true synonym and is left unglossed rather than duplicated
UPDATE "cards" SET "swedish" = 'ingenstans'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3806;

-- rank 1823: Swedish "undervisning" pins der Unterricht (instruction/classes)
UPDATE "cards" SET "swedish" = 'undervisning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1823;

-- rank 2678: Swedish "författning, grundlag" pins die Verfassung — ver+fassung = för+fattning, the same fassen/fatta root as zusammenfassen→sammanfatta
UPDATE "cards" SET "swedish" = 'författning, grundlag'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2678;

-- rank 626: irgendwie is the vague adverb: "på något sätt" (wie → sätt), no "alls" reading
UPDATE "cards" SET "swedish" = 'på något sätt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 626;

-- rank 764: irgendwann is vague "någon gång" (wann → gång), vs. the free-choice jederzeit→när som helst (3162)
UPDATE "cards" SET "swedish" = 'någon gång'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 764;

-- rank 1120: irgendetwas is the pronoun, so it carries the at-all reading: Hast du irgendetwas gesagt? = Sa du någonting alls?
UPDATE "cards" SET "swedish" = 'någonting alls'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1120;

-- rank 1118: irgendein carries the at-all/free-choice reading (irgendeinen Rat = något råd alls); "vilken" mirrors the determiner
UPDATE "cards" SET "swedish" = 'något alls, vilken som helst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1118;

-- rank 1911: irgendwelche is the plural of irgendein and Swedish pluralises identically (vilken → vilka)
UPDATE "cards" SET "swedish" = 'några alls, vilka som helst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1911;

-- rank 4941: irgendjemand takes "vem som helst" where irgendein takes "vilken som helst" — vem/vilken mirrors jemand/ein exactly
UPDATE "cards" SET "swedish" = 'någon alls, vem som helst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4941;

-- rank 3619: bare irgend is the fixed "irgend so ein" construction, not the productive prefix, so "någon sorts" is a rough fit rather than a clean one
UPDATE "cards" SET "swedish" = 'någon sorts'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3619;

-- rank 32: Swedish "man" is the same word doing the same job as German man; English needs one/you/they for it
UPDATE "cards" SET "swedish" = 'man'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 32;

-- rank 87: Swedish "varje" pins jede (every)
UPDATE "cards" SET "swedish" = 'varje'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 87;

-- rank 100: etwas spans the pronoun and the adverbial "a little" its example tests (macht die Welt etwas besser = lite bättre), so the gloss carries both
UPDATE "cards" SET "swedish" = 'något; lite (bättre)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 100;

-- rank 109: Swedish "ingenting" pins nichts (nothing), the negative counterpart to etwas→något
UPDATE "cards" SET "swedish" = 'ingenting'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 109;

-- rank 174: Swedish "några" pins einige (a few/some)
UPDATE "cards" SET "swedish" = 'några'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 174;

-- rank 330: Swedish "någon" pins jemand (someone) — the plain form that makes irgendjemand→någon alls readable
UPDATE "cards" SET "swedish" = 'någon'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 330;

-- rank 362: Swedish "ingen" pins niemand (nobody), the negative counterpart to jemand→någon
UPDATE "cards" SET "swedish" = 'ingen'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 362;

-- rank 433: Swedish "somliga, vissa" pins manche (some people/many a), distinct from einige→några
UPDATE "cards" SET "swedish" = 'somliga, vissa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 433;
