-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

-- rank 374: The CONJUNCTION damit (so that/in order that) — homograph of rank-119 damit (with it) — is purpose, Swedish "för att"; "så att" (result) moved to its cognate sodass (1512)
UPDATE "cards" SET "swedish" = 'för att'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 374;

-- rank 792: Swedish "således" pins somit (consequently/thus): so-mit = så-ledes, and it stays off damit→därmed (119) and also→alltså (71), the true cognate
UPDATE "cards" SET "swedish" = 'således'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 792;

-- rank 1227: demnach is "according to that, therefore" (Es gibt demnach nur zwei Möglichkeiten); "enligt detta" exposes dem-nach = detta-enligt, with "följaktligen" on its cognate folglich (3669), "alltså" on its cognate also (71) and "således" on somit (792)
UPDATE "cards" SET "swedish" = 'enligt detta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1227;

-- rank 678: Swedish "såväl . . . som" is the exact pair for sowohl . . . als auch
UPDATE "cards" SET "swedish" = 'såväl . . . som'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 678;

-- rank 766: Swedish "varken . . . eller" is the exact pair for weder . . . noch
UPDATE "cards" SET "swedish" = 'varken . . . eller'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 766;

-- rank 368: Swedish "prata" matches reden as the everyday word for talking, leaving "tala" for the more formal sprechen
UPDATE "cards" SET "swedish" = 'prata'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 368;

-- rank 759: Swedish "tal" is the exact match for die Rede (a speech); the "number" sense on die Zahl is told apart by the English prompt
UPDATE "cards" SET "swedish" = 'tal'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 759;

-- rank 58: machen spans "do" and "make"; Swedish "göra; laga, tillverka" carries both, leaving plain "göra" for tun so the two "to do" cards stay apart
UPDATE "cards" SET "swedish" = 'göra; laga, tillverka'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 58;

-- rank 646: Swedish "prestation" is the exact match for die Leistung (performance, achievement)
UPDATE "cards" SET "swedish" = 'prestation'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 646;

-- rank 693: Swedish "prestera, åstadkomma" pins leisten (to perform, achieve) and ties it to Leistung→prestation
UPDATE "cards" SET "swedish" = 'prestera, åstadkomma'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 693;

-- rank 760: Swedish "stödja" is the everyday word for unterstützen (to support); the cognate "understödja" is stilted
UPDATE "cards" SET "swedish" = 'stödja'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 760;

-- rank 1141: Swedish "stöd" pins die Unterstützung (support), pairing with unterstützen→stödja
UPDATE "cards" SET "swedish" = 'stöd'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1141;

-- rank 3519: unterstellen covers "put under someone" (the example: underställd, as in an org chart) and "insinuate"; Swedish needs a word for each
UPDATE "cards" SET "swedish" = 'underställa; insinuera'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3519;

-- rank 4347: Swedish "stryka under" is the literal underline the example tests, leaving "betona" free for betonen
UPDATE "cards" SET "swedish" = 'stryka under'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4347;

-- rank 123: Swedish "göra" pins tun (to do); machen carries the extra "make" senses, so the two "to do" cards differ in Swedish
UPDATE "cards" SET "swedish" = 'göra'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 123;

-- rank 173: während is both "while" (conjunction, the example) and "during" (preposition); Swedish splits them as medan / under
UPDATE "cards" SET "swedish" = 'medan; under'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 173;

-- rank 666: Swedish "genom att" is exactly how indem works (by doing X), which the English "while, by" blurs
UPDATE "cards" SET "swedish" = 'genom att'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 666;

-- rank 1631: Swedish "ett tag" is the everyday match for eine Weile (a while); "en stund" would be just as good but primes the false friend die Stunde (hour)
UPDATE "cards" SET "swedish" = 'ett tag'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1631;

-- rank 449: Swedish "beslut" is the everyday word for die Entscheidung (decision); der Beschluss (beslut's direct cognate) is split off as "resolution, formellt beslut"
UPDATE "cards" SET "swedish" = 'beslut'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 449;

-- rank 3290: Swedish "åtskillnad" pins die Unterscheidung (making a distinction), keeping plain "skillnad" free for der Unterschied (difference)
UPDATE "cards" SET "swedish" = 'åtskillnad'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3290;

-- rank 799: Swedish "val" covers both senses of die Wahl (a choice, an election)
UPDATE "cards" SET "swedish" = 'val'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 799;

-- rank 2064: Swedish "urval" pins die Auswahl (a selection to pick from), apart from Wahl→val
UPDATE "cards" SET "swedish" = 'urval'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2064;

-- rank 414: three "to decide" verbs: entscheiden→avgöra (its structural twin: ent-scheiden = av-göra) + "bestämma sig" for the reflexive sich entscheiden the example tests; bestimmen→bestämma, beschließen→besluta
UPDATE "cards" SET "swedish" = 'avgöra; bestämma sig'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 414;

-- rank 905: Swedish "avgörande" is the exact match for entscheidend (decisive), pairing with entscheiden→avgöra
UPDATE "cards" SET "swedish" = 'avgörande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 905;

-- rank 1073: Swedish "besluta" is the live cognate of beschließen (to decide, formally resolve), apart from entscheiden→avgöra and bestimmen→bestämma
UPDATE "cards" SET "swedish" = 'besluta'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1073;

-- rank 3220: der Beschluss is a formal decision/resolution; "resolution, formellt beslut" keeps it apart from die Entscheidung→beslut
UPDATE "cards" SET "swedish" = 'resolution, formellt beslut'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3220;

-- rank 636: Swedish "välja" covers wählen in both senses, choose and elect (välja en ny kansler, as in the example)
UPDATE "cards" SET "swedish" = 'välja'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 636;

-- rank 1884: Swedish "välja ut" mirrors aus-wählen (to pick out), apart from plain wählen→välja
UPDATE "cards" SET "swedish" = 'välja ut'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1884;

-- rank 2518: Swedish "väljare" is the exact match for der Wähler (voter)
UPDATE "cards" SET "swedish" = 'väljare'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2518;

-- rank 2911: Swedish "valrörelse" is the everyday word for der Wahlkampf (election campaign)
UPDATE "cards" SET "swedish" = 'valrörelse'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2911;

-- rank 3802: Swedish "mandatperiod" is the everyday word for die Wahlperiode (term of office between elections)
UPDATE "cards" SET "swedish" = 'mandatperiod'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3802;

-- rank 399: Swedish "röst" covers both senses of die Stimme (voice, vote), just like German
UPDATE "cards" SET "swedish" = 'röst'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 399;

-- rank 490: stimmen is "be correct" (Swedish cognate: det stämmer) and "vote for/against" (the example: stimmen gegen = röstar emot)
UPDATE "cards" SET "swedish" = 'stämma; rösta för/emot'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 490;

-- rank 2802: abstimmen is "vote on" (the example) and "coordinate", where Swedish "stämma av" is its live cognate
UPDATE "cards" SET "swedish" = 'rösta om; stämma av'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2802;

-- rank 2994: die Abstimmung mirrors abstimmen: a vote (omröstning, the example) and a coordination (avstämning)
UPDATE "cards" SET "swedish" = 'omröstning; avstämning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2994;

-- rank 2507: Swedish "instämma" is the live cognate of zustimmen (to agree with); "hålla med" is the everyday phrasing
UPDATE "cards" SET "swedish" = 'instämma, hålla med'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2507;

-- rank 2737: Swedish "samtycke" pins die Zustimmung (consent, approval) as in the example (parents give consent)
UPDATE "cards" SET "swedish" = 'samtycke'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2737;

-- rank 3289: Swedish "stämma överens" is the exact match for übereinstimmen (to correspond, agree)
UPDATE "cards" SET "swedish" = 'stämma överens'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3289;

-- rank 4901: Swedish "överensstämmelse" is the exact match for die Übereinstimmung (match, agreement)
UPDATE "cards" SET "swedish" = 'överensstämmelse'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4901;

-- rank 1728: Swedish "stämning" is the exact match for die Stimmung (mood, atmosphere)
UPDATE "cards" SET "swedish" = 'stämning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1728;

-- rank 1586: Swedish "bestämmelse" is the live cognate of die Bestimmung in its regulation sense, the one the example tests
UPDATE "cards" SET "swedish" = 'bestämmelse'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1586;

-- rank 160: Swedish "följa" is the live cognate of folgen (to follow)
UPDATE "cards" SET "swedish" = 'följa'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 160;

-- rank 431: Swedish "följd" is the live cognate of die Folge (consequence), keeping "konsekvens" free for die Konsequenz
UPDATE "cards" SET "swedish" = 'följd'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 431;

-- rank 386: Swedish "resultat" is the everyday word for das Ergebnis (result); the rarer das Resultat (its direct cognate) can be split off later
UPDATE "cards" SET "swedish" = 'resultat'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 386;

-- rank 541: Swedish "framgång" is the everyday word for der Erfolg (success)
UPDATE "cards" SET "swedish" = 'framgång'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 541;

-- rank 735: Swedish "framgångsrik" pairs erfolgreich (successful) with Erfolg→framgång
UPDATE "cards" SET "swedish" = 'framgångsrik'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 735;

-- rank 1150: Swedish "förfölja" is the live cognate of verfolgen; "jaga" fits the chase in the example (von der Polizei verfolgt)
UPDATE "cards" SET "swedish" = 'förfölja, jaga'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1150;

-- rank 2996: Swedish "efterträda" is the exact match for nachfolgen in the succeed-in-office sense the example tests
UPDATE "cards" SET "swedish" = 'efterträda'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2996;

-- rank 2781: Swedish "efterträdare" pairs der Nachfolger (successor) with nachfolgen→efterträda
UPDATE "cards" SET "swedish" = 'efterträdare'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2781;

-- rank 3311: Swedish "ordningsföljd" is the exact match for die Reihenfolge (order, sequence)
UPDATE "cards" SET "swedish" = 'ordningsföljd'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3311;

-- rank 3669: Swedish "följaktligen" is the live cognate of folglich (consequently)
UPDATE "cards" SET "swedish" = 'följaktligen'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3669;

-- rank 3380: Swedish "till följd av" is the exact match for infolge (as a result of)
UPDATE "cards" SET "swedish" = 'till följd av'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3380;

-- rank 1413: Swedish "enligt" is the everyday match for zufolge (according to, as in the example: dem Arzt zufolge = enligt läkaren)
UPDATE "cards" SET "swedish" = 'enligt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1413;

-- rank 1582: Swedish "konsekvens" is the live cognate of die Konsequenz, apart from die Folge→följd
UPDATE "cards" SET "swedish" = 'konsekvens'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1582;

-- rank 2142: resultieren aus (the example) is Swedish "bero på / komma av", which also keeps it apart from ergeben→resultera i
UPDATE "cards" SET "swedish" = 'bero på, komma av'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2142;

-- rank 2848: Swedish has one word for both das Ergebnis and das Resultat; Ergebnis gets plain "resultat", and "(lånordet)" points at the German loanword Resultat
UPDATE "cards" SET "swedish" = 'resultat (lånordet)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2848;

-- rank 3797: der Befund is a (medical) finding; Swedish "provsvar" fits the example (my findings are negative), "fynd" the general sense
UPDATE "cards" SET "swedish" = 'provsvar; fynd'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3797;

-- rank 859: Swedish "främmande" is the exact match for fremd (foreign, strange)
UPDATE "cards" SET "swedish" = 'främmande'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 859;

-- rank 3770: Swedish "främmande språk" mirrors die Fremdsprache (foreign language) and pairs it with fremd→främmande
UPDATE "cards" SET "swedish" = 'främmande språk'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3770;

-- rank 4285: Swedish "främling" is the exact match for der Fremde (stranger)
UPDATE "cards" SET "swedish" = 'främling'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4285;

-- rank 793: bezahlen leans to a direct object, the thing or person paid for (das Essen bezahlen); "betala (för något)" marks that against zahlen→betala (ett belopp). The source example paid an amount (Wie viel hast du bezahlt?), which is zahlen territory, so it now pays for a thing
UPDATE "cards" SET "swedish" = 'betala (för något)', "example_de" = 'Hast du das Essen schon bezahlt?', "example_en" = 'Have you already paid for the food?'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 793;

-- rank 832: zahlen leans to an amount or no object (50 Euro zahlen, Zahlen bitte!); "betala (ett belopp)" marks that against bezahlen→betala (för något). The source example paid a bill (die Rechnung zahlen), which is bezahlen territory, so it now asks about an amount
UPDATE "cards" SET "swedish" = 'betala (ett belopp)', "example_de" = 'Wie viel muss ich zahlen?', "example_en" = 'How much do I have to pay?'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 832;

-- rank 740: Swedish "räkna" is the live cognate of rechnen (to calculate), apart from berechnen→beräkna
UPDATE "cards" SET "swedish" = 'räkna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 740;

-- rank 857: Swedish "beräkna" is the be- cognate of berechnen (to calculate, the example: berechnen die Kosten = beräknar kostnaderna)
UPDATE "cards" SET "swedish" = 'beräkna'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 857;

-- rank 1754: Swedish "beräkning" pairs die Berechnung with berechnen→beräkna
UPDATE "cards" SET "swedish" = 'beräkning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1754;

-- rank 1856: Swedish "räkning" is the live cognate of die Rechnung (bill); "faktura" covers the invoice in the example
UPDATE "cards" SET "swedish" = 'räkning, faktura'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1856;

-- rank 3365: der Rechner is a computer (the example) or a calculator; Swedish uses dator / räknare
UPDATE "cards" SET "swedish" = 'dator; räknare'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3365;

-- rank 4824: Swedish "räkna om" mirrors um-rechnen (to convert, e.g. prices into another currency)
UPDATE "cards" SET "swedish" = 'räkna om'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4824;

-- rank 1835: ausgerechnet is "of all people/times"; Swedish says "just idag, av alla dagar", as in the example (ausgerechnet heute)
UPDATE "cards" SET "swedish" = 'just (av alla dagar)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1835;

-- rank 853: Swedish "antal" is the live cognate of die Anzahl (number of), apart from die Zahl→tal
UPDATE "cards" SET "swedish" = 'antal'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 853;

-- rank 919: Swedish "talrik" is the live cognate of zahlreich (numerous), built on Zahl→tal like the German
UPDATE "cards" SET "swedish" = 'talrik'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 919;

-- rank 2864: Swedish "en mängd" is the everyday match for eine Vielzahl (a multitude)
UPDATE "cards" SET "swedish" = 'mängd, mångfald'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2864;

-- rank 3314: Swedish "betalning" pairs die Zahlung (payment) with zahlen→betala
UPDATE "cards" SET "swedish" = 'betalning'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 3314;

-- rank 28: Swedish "så" is the live cognate of so, covering the manner sense of the example (so wie er = så som han)
UPDATE "cards" SET "swedish" = 'så'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 28;

-- rank 71: German also is a false friend for English "also": it means "so, thus", exactly Swedish "alltså", its cognate
UPDATE "cards" SET "swedish" = 'alltså'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 71;

-- rank 2663: Swedish "så pass" matches derart as an intensifier before a dass-clause (derart nervös, dass = så pass nervös att)
UPDATE "cards" SET "swedish" = 'så pass'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 2663;

-- rank 1512: Swedish "så att" is the exact match for sodass (result: so that), apart from damit→för att (purpose)
UPDATE "cards" SET "swedish" = 'så att'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1512;

-- rank 1272: Swedish "så att säga" is the exact match for sozusagen (so to speak)
UPDATE "cards" SET "swedish" = 'så att säga'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1272;

-- rank 4004: Swedish "på sätt och vis" matches gewissermaßen (as it were), keeping it apart from sozusagen→så att säga
UPDATE "cards" SET "swedish" = 'på sätt och vis'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 4004;

-- rank 185: Swedish "sådan" is the live cognate of solch (such)
UPDATE "cards" SET "swedish" = 'sådan'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 185;

-- rank 549: Swedish "så kallad" is the exact match for sogenannt (so-called)
UPDATE "cards" SET "swedish" = 'så kallad'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 549;

-- rank 1833: Swedish "såvitt" is the exact match for soweit as in the example (soweit ich weiß = såvitt jag vet)
UPDATE "cards" SET "swedish" = 'såvitt'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 1833;

-- rank 281: sowie is "as well as" (the example: Männer sowie Frauen = män liksom kvinnor) and "as soon as"; Swedish needs a word for each, and "samt" is left for German samt
UPDATE "cards" SET "swedish" = 'liksom; så snart som'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 281;

-- rank 535: Swedish "likaså" pins ebenso (just as, likewise); "lika" fits the comparison in the example (ebenso gerne wie = lika gärna som)
UPDATE "cards" SET "swedish" = 'likaså, lika'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 535;

-- rank 808: Swedish "precis lika" matches genauso (exactly as), apart from ebenso→likaså
UPDATE "cards" SET "swedish" = 'precis lika'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 808;

-- rank 226: Swedish "till och med" is the everyday match for sogar (even)
UPDATE "cards" SET "swedish" = 'till och med'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 226;

-- rank 446: Swedish "genast" is the everyday match for sofort (immediately)
UPDATE "cards" SET "swedish" = 'genast'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 446;

-- rank 336: Swedish "annars" is the exact match for sonst (otherwise)
UPDATE "cards" SET "swedish" = 'annars'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 336;

-- rank 607: Swedish "skilja på" is the everyday match for unterscheiden (the example: links und rechts nicht unterscheiden = inte skilja på höger och vänster), in the same family as unterschiedlich→skilda
UPDATE "cards" SET "swedish" = 'skilja (på)'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 607;

-- rank 632: Swedish "skillnad" is the exact match for der Unterschied (difference), apart from die Unterscheidung→åtskillnad
UPDATE "cards" SET "swedish" = 'skillnad'
WHERE "deck_id" = 'b7c8e3a0-6d4f-4e2a-9c1b-000000005000'::uuid AND "frequency_rank" = 632;
