// Apply the word-corpus override table (server/db/words-overrides.ts) to the
// committed corpus and emit the matching backfill migration. The regen-free
// counterpart to scripts/gen-words.ts: gen-words rebuilds everything from the
// source .apkg (applying overrides last); this script only re-applies the table to
// the committed words.data.json, so day-to-day card fixes need no Anki source.
//
// Usage:  npx tsx scripts/apply-overrides.ts [--name=<snake_case_migration_name>]
//
// - Nothing changed (data.json already reflects the table): says so, writes nothing.
// - Something changed: rewrites server/db/words.data.json, writes
//   drizzle/00NN_<name>.sql with one in-place UPDATE per changed rank (idempotent,
//   keyed on (deck_id, frequency_rank) so review progress is preserved), and
//   appends the entry to drizzle/meta/_journal.json. Review the SQL, run
//   `npm run check`, and commit all three together. `npm run db:migrate` applies it
//   to your dev branch; prod gets it from the CI migrate job on push to main.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ParsedWord } from "../server/db/words-parse.ts";
import {
  WORD_OVERRIDES,
  applyOverrides,
  overrideUpdateSql,
} from "../server/db/words-overrides.ts";

const root = join(import.meta.dirname, "..");
const dataPath = join(root, "server", "db", "words.data.json");
const journalPath = join(root, "drizzle", "meta", "_journal.json");

const name =
  process.argv.find((a) => a.startsWith("--name="))?.slice("--name=".length) ??
  "word_overrides";
if (!/^[a-z0-9_]+$/.test(name)) {
  console.error(`--name must be snake_case (got "${name}")`);
  process.exit(1);
}

const words = JSON.parse(readFileSync(dataPath, "utf8")) as ParsedWord[];
const applied = applyOverrides(words); // throws if the table is stale — see module docs

// Only overrides whose target row actually changed get a new UPDATE — ones already
// shipped in an earlier backfill (or already baked into a regen) are settled.
const changed = WORD_OVERRIDES.filter((o) => {
  const i = words.findIndex((w) => w.frequencyRank === o.rank);
  return JSON.stringify(applied[i]) !== JSON.stringify(words[i]);
});

if (changed.length === 0) {
  console.log("words.data.json already reflects every override — nothing to do.");
  process.exit(0);
}

// --- words.data.json (same compact format as gen-words.ts) ---
writeFileSync(dataPath, JSON.stringify(applied, null, 0) + "\n");

// --- the next migration + its journal entry ---
const journal = JSON.parse(readFileSync(journalPath, "utf8")) as {
  entries: { idx: number; version: string; when: number; tag: string; breakpoints: boolean }[];
  [k: string]: unknown;
};
const idx = journal.entries[journal.entries.length - 1].idx + 1;
const tag = `${String(idx).padStart(4, "0")}_${name}`;

const header = `-- Backfill: apply word-corpus overrides (server/db/words-overrides.ts) to the live
-- cards. Generated by scripts/apply-overrides.ts — per-fix reasons inline below.
-- UPDATEs cards IN PLACE, keyed on (deck_id, frequency_rank): no deck delete/recreate,
-- so every user's review_state/reviews (progress) is preserved. Idempotent: re-running
-- sets the same values. Applied to dev via db:migrate and to prod by the CI migrate
-- job on push to main.

`;
const sqlPath = join(root, "drizzle", `${tag}.sql`);
writeFileSync(sqlPath, header + changed.map(overrideUpdateSql).join("\n"));

journal.entries.push({ idx, version: "7", when: Date.now(), tag, breakpoints: true });
writeFileSync(journalPath, JSON.stringify(journal, null, 2) + "\n");

console.log(
  `Applied ${changed.length} override(s) (rank ${changed.map((o) => o.rank).join(", ")}).\n` +
    `  → ${dataPath}\n  → ${sqlPath}\n  → ${journalPath}\n` +
    `Review the SQL, run \`npm run check\`, and commit all three together.`,
);
